Repository gravitational/webapps, pull requests merged in 2022-03, with the labels that each got.

#635 Maintain aspect ratio on Desktop Playback
  packages/teleport/src/Player/DesktopPlayer.tsx
  packages/teleport/src/Player/ProgressBar/ProgressBar.tsx
  packages/teleport/src/Player/ProgressBar/ProgressBarDesktop.tsx
  packages/teleport/src/Player/ProgressBar/index.tsx
Labels: backport-required, test-plan-issue

#608 Update FormLogin.tsx
  packages/shared/components/FieldInput/FieldInput.tsx
  packages/teleport/src/components/FormLogin/FormLogin.tsx
  packages/teleport/src/components/FormLogin/__snapshots__/FormLogin.story.test.tsx.snap
Labels: enhancement

#638 desktop playback error handling
  packages/teleport/src/Player/DesktopPlayer.tsx
  packages/teleport/src/Player/ProgressBar/ProgressBarDesktop.tsx
  packages/teleport/src/lib/tdp/client.ts
  packages/teleport/src/lib/tdp/playerClient.ts
Labels: backport-required, test-plan-issue

#652 v9 backports
  packages/teleport/src/DesktopSession/DesktopSession.story.tsx
  packages/teleport/src/DesktopSession/DesktopSession.tsx
  packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx
  packages/teleport/src/Player/DesktopPlayer.tsx
  packages/teleport/src/Player/ProgressBar/ProgressBar.tsx
  packages/teleport/src/Player/ProgressBar/ProgressBarDesktop.tsx
  packages/teleport/src/Player/ProgressBar/index.tsx
  packages/teleport/src/components/TdpClientCanvas/TdpClientCanvas.tsx
  packages/teleport/src/lib/tdp/client.ts
  packages/teleport/src/lib/tdp/playerClient.ts
Labels: desktop-access, merge-for-v9, test-plan-issue
